seed: 42
device: cuda
tokenizer_dir: tokenizer
epochs: 3
micro_batch_size: 4
learning_rate: 0.00003
weight_decay: 0.01
max_seq_len: 2048
clip_norm: 1.0
tokens_per_step: 32768
log_every_update: 100
save_per_step: 10000
base_model_ckpt: pretrained/pretrain_final.pt
out_dir: sft_mid

mixed_dataset_config:
- mixed_dataset: 
    name: Alpaca
    weight: 0.8
- mixed_dataset:
    name: Dolly
    weight: 0.2